### ISSUE TITLE
DB Error: [1062] Duplicate entry

### ISSUE THREAD

**Issue by sirszabo** [ashabada/login_history#1]
Hello,

I am try to implement your plugin, but I get the duplicate entry if I login from static IP.
Here is my errorlog:

[09-Feb-2016 23:59:40 +0100]: <b9pt08k9> DB Error: [1062] Duplicate entry 'TEST USER' for key 'PRIMARY' (SQL Query: INSERT INTO login_logs(username, remoteip, remotedns, logintime)
                                                VALUES('TEST USER', '79.120.xxx.xx', 'xxxx.awknet.hu', NOW())) in /-webpath-/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login?_task=login&_action=login)
[10-Feb-2016 00:02:13 +0100]: <jthcnu54> DB Error: [1062] Duplicate entry 'TEST USER' for key 'PRIMARY' (SQL Query: INSERT INTO login_logs(username, remoteip, remotedns, logintime)
                                                VALUES('TEST USER', '79.120.xxx.xx', 'xxxx.awknet.hu', NOW())) in /-webpath-/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login?_task=login&_action=login)

Could you please check it?! 
Many thanks!

**Comment by ashabada** [comment]
Hello.
I look into this tomorrow. At the moment try to remove primary key by running "ALTER TABLE login_logs DROP INDEX `PRIMARY`;".

**Comment by sirszabo** [comment]
Hello ashabada,

Thanks for your feedback! Of course I can wait!
I am already deleted the primary key.

mysql> drop index `PRIMARY` on login_logs;
Query OK, 42 rows affected (0.02 sec)
Records: 42  Duplicates: 0  Warnings: 0

Now the inserting entries is okay on the MySQL, but the select when I try to show the info is empty on the webmail.

Some background info
Roundcube: 1.1.4
MySQL: 5.6.27
php: 5.5.9

Regards,
Zoltan

**Comment by ashabada** [comment]
Hey.

So i removed primary key from mysql.initial.sql. Dunno why it was there in first place :)
It should work ok now. Did a quick testrun just to see if everything works ok on Roundcube 1.1.4, PHP 5.4.16, Centos 7, MariaDB 5.5.44-2/MySQL 5.1.73-5 just in case, but its obvious that primary key were to blame.

**Comment by sirszabo** [comment]
Hello,

Now, I see the new login insert rows. But if I try to check the "last login" the page is empty. The strange is I didn't see any error in the logs ...

**Comment by sirszabo** [comment]
![loginhistory_display](https://cloud.githubusercontent.com/assets/17151973/12958703/4aeb1470-d033-11e5-9c8c-e07ced7fbd2a.png)

**Comment by ashabada** [comment]
Can you turn on mysql query logs to see if select query runs at all? 
Also do you seen correct last login info in upper right corner when logged in? Like ip and date?

**Comment by sirszabo** [comment]
I nothing to see in the upper right corner. I just see the "- -". 
Need some minutes to activate the query logs. But as I see it is problem with the showinfo section. If I put the "SELECT remoteip, remotedns, logintime FROM login_logs WHERE username = TEST USER ORDER BY logintime;" I get the error. But if I type with "TEST USER" than I get back the info!

**Comment by sirszabo** [comment]
Okay, I catch it the problem ... In my system the username is test.user@domain.hu. But in the login_logs table I see the user full name like TEST USER in the username row. When the system try to get the user last login data, it is fails, because the username is test.user@domain.hu not TEST USER.

**Comment by sirszabo** [comment]
in the login_history.php the line 47, 48

$identity = $user->get_identity();
$username = $identity['name'];

The identity "validation" is not okay for me, because I am use my webmail in multiple domain.

**Comment by ashabada** [comment]
ok, let me check, i think i know where is the problem.

**Comment by sirszabo** [comment]
I changed the $username = $identity['name']; to $username = $identity['email']; and now it is okay. I can get the last logs!

**Comment by sirszabo** [comment]
Plus in the line 68 the 'name' also changed to 'email'. Now everything is work as need! :)

**Comment by ashabada** [comment]
Yes, you beat me to it. Nice catch :)

**Comment by sirszabo** [comment]
I just helped to you! ;) I happy to use this plugin, so if I can help I will! :D 
I close this issue, now your plugin works on a multiple domain webmail server!
Thanks for your help!

**Comment by ashabada** [comment]
Cheers. Ill tinker a bit with plugin to see if there are no logical errors of some sorts and then update.

**Comment by sirszabo** [comment]
Okay! At tomorrow (night) I will report you, when my users login to the website back. Now as I see on my 43 users (currently logged in), the modification is working perfectly!

**Comment by ashabada** [comment]
I chose to use login name everywhere explicitly. I assume your changes works in your environment because your login = email. In case someone has login "test.user" that would not work. Also user  controls email variable when editing his identity in settings.

**Comment by sirszabo** [comment]
Yeah, you are right! I update my settings with your 1.01 version! Now 34 user is online in my system, so I can see the logs. I just kill they sessions with save the current data ...

**Comment by sirszabo** [comment]
I just updated ... Unfortunately not working. The insert is same, I see the username as identity. And the select also failed because of the login = email.

**Comment by sirszabo** [comment]
ashadaba: can we continue the communication on facebook/gmail chat? if you have time right now, I can help to you! My name is Zoltan Szabo (https://www.facebook.com/sirszabo) or sirszabo@gmail.com. I will delete this message in the next 15 minutes! :)

**Comment by ashabada** [comment]
Gtalk then

**Comment by sirszabo** [comment]
or e-mail me to sirszabo@awknet.hu ...

**Comment by sirszabo** [comment]
Your update working like as a charm! :) Thanks a lot!
