### ISSUE TITLE
[Feature request] Add option for get GEO info about IP address

### ISSUE THREAD

**Issue by MurzNN** [ashabada/login_history#3]
Will be good to have optionally enable getting GEO info about IP address, for example, via http://ipinfo.io/ site. But this will be good in background, because receiving geo info maybe not so quick, so this will slow-down login process, if executed in login script.

**Comment by ashabada** [comment]
I will think about it. Maybe integrate geoip. Remote lookup apis will definately not work imo. Various timeouts, slow responses, limited free lookups, plaintext api access, getting api keys would be to mutch  hustle

**Comment by ashabada** [comment]
Updated to support GeoIP2.
